name: Release flatpak

on:
  push:
    tags: "v*.*.*"

jobs:
  flatpak:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
            bundle: lipl-control-x64.flatpak
            manifest-path: nl.paulmin.lipl.Control.yml
            cache-key: flatpak-builder-${{ github.sha }}
            gpg-sign: info@paulmin.nl
      - name: Calculate checksum
        run: sha256sum lipl-control-x64.flatpak > lipl-control-x64.flatpak.sig.txt
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "lipl-control-x64.flatpak,lipl-control-x64.flatpak.sig.txt"
